name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint:code
      - name: Lint styling
        run: npm run lint:style
      - name: Run unit tests
        run: npm run test:unit:coverage
      - name: Run mutation tests
        run: npm run test:mutation -- --reporters=clear-text
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
